### ISSUE TITLE
Stacktrace on `lein figwheel`

### ISSUE THREAD

**Issue by chrismurrph** [bhauman/devcards-template#10]
This is on Windows 7. Following the straightforward instructions causes a crash, with an `analyzer` file not being found. 

C:\dev>lein new devcards cardssystem
Retrieving devcards/lein-template/0.2.1-3/lein-template-0.2.1-3.pom from clojars

Retrieving devcards/lein-template/0.2.1-3/lein-template-0.2.1-3.jar from clojars

Generating fresh 'lein new' devcards project.
cd into your project directory
Run 'lein figwheel' and then open localhost:3449/cards.html in your browser.
C:\dev>cd cardssystem

C:\dev\cardssystem>lein figwheel
Retrieving lein-figwheel/lein-figwheel/0.5.0-1/lein-figwheel-0.5.0-1.pom from cl
ojars
Retrieving figwheel-sidecar/figwheel-sidecar/0.5.0-1/figwheel-sidecar-0.5.0-1.po
m from clojars
Retrieving org/clojure/tools.reader/1.0.0-alpha1/tools.reader-1.0.0-alpha1.pom f
rom central
Retrieving figwheel/figwheel/0.5.0-1/figwheel-0.5.0-1.pom from clojars
Retrieving figwheel-sidecar/figwheel-sidecar/0.5.0-1/figwheel-sidecar-0.5.0-1.ja
r from clojars
Retrieving lein-figwheel/lein-figwheel/0.5.0-1/lein-figwheel-0.5.0-1.jar from cl
ojars
Retrieving figwheel/figwheel/0.5.0-1/figwheel-0.5.0-1.jar from clojars
clojure.lang.Compiler$CompilerException: java.io.FileNotFoundException: Could no
t locate cljs/analyzer__init.class or cljs/analyzer.clj on classpath: , compilin
g:(figwheel_sidecar/utils.clj:1:1)
 at clojure.lang.Compiler.load (Compiler.java:7142)
    clojure.lang.RT.loadResourceScript (RT.java:370)
    clojure.lang.RT.loadResourceScript (RT.java:361)
    clojure.lang.RT.load (RT.java:440)
    clojure.lang.RT.load (RT.java:411)
    clojure.core$load$fn__5066.invoke (core.clj:5641)
    clojure.core$load.doInvoke (core.clj:5640)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$load_one.invoke (core.clj:5446)
    clojure.core$load_lib$fn__5015.invoke (core.clj:5486)
    clojure.core$load_lib.doInvoke (core.clj:5485)
    clojure.lang.RestFn.applyTo (RestFn.java:142)
    clojure.core$apply.invoke (core.clj:626)
    clojure.core$load_libs.doInvoke (core.clj:5524)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invoke (core.clj:626)
    clojure.core$require.doInvoke (core.clj:5607)
    clojure.lang.RestFn.invoke (RestFn.java:551)
    figwheel_sidecar.config$eval651$loading__4958__auto____652.invoke (config.cl
j:1)

**Comment by bhauman** [comment]
Upgrade to leinigen 2.5.3

**Comment by chrismurrph** [comment]
Wow thanks. 
`lein upgrade` did the trick and can see my first devcard.
