### ISSUE TITLE
Fix exception for Java 9

### ISSUE THREAD

**Issue by mathieuroblin** [bhauman/devcards-template#24]
I am encountering an Exception when I am trying to start a new project using this template. 

I saw in another [thread](https://github.com/bhauman/lein-figwheel/issues/612) that the fix is to add `:jvm-opts ["--add-modules" "java.xml.bind"]` in project.clj

I noticed the fixed has been introduced in [figwheel-template](https://github.com/bhauman/figwheel-template/commit/627fa1d95d19682ebcc39627c2785eaa70482e22) to support Java 9 when the project is created but I don't see such thing in devcards-template.

Is it possible to fix this ? I can take care of it if need be.

**Comment by bhauman** [comment]
yes feel free to send a PR :)

**Comment by tirkarthi** [comment]
I think this is fixed with https://github.com/bhauman/devcards-template/commit/a76dae3ff0d7c323d4818514e7654133ab4e046a and can be closed
